### ISSUE TITLE
Contract violation (index access/global resolve) on com.phpuaca.completion.ProphecyTypeProvider.getType

### ISSUE THREAD

**Issue by neuro159** [maxfilatov/phpuaca#27]
**We gonna ban the plugin in next build if following is not fixed
YOU CANT CALL GLOBL RESOLVE OR ACCESS INDEXES YOURSELF from  PhpTypeProvider.getType!!!
Please contact me ASAP if you need an assistance.**

com.intellij.util.indexing.IndexAccessValidator.checkAccessingIndexDuringOtherIndexProcessing
....
    at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.resolve(VariableImpl.java:352)
    at com.phpuaca.completion.ProphecyTypeProvider.getTypeForVariable(ProphecyTypeProvider.java:177)
    at com.phpuaca.completion.ProphecyTypeProvider.getType(ProphecyTypeProvider.java:56)
....

```
at com.phpuaca.util.PhpMethodResolver.resolveByMethodReference(PhpMethodResolver.java:15)
at com.phpuaca.completion.PHPUnitTypeProvider.getType(PHPUnitTypeProvider.java:54)
```

**Comment by maxfilatov** [comment]
Hi @neuro159 

Type providers has been temporary removed from plugin, so problem should be "solved".
I'll reimplement it a little bit later without accessing to indexes.
Your previous message I understood incorrect like "use dumb service checks and keep calm", sorry :(

**Comment by scflode** [comment]
@maxfilatov are you still planing on implementing type providers again? It is super useful. Anything one can with help on this?

**Comment by amakhrov** [comment]
@maxfilatov any news on that?

**Comment by Haehnchen** [comment]
reimplemented in fork https://github.com/Haehnchen/idea-php-phpunit-plugin
