### ISSUE TITLE
contract violation It's prohibited to access index during event dispatching

### ISSUE THREAD

**Issue by neuro159** [maxfilatov/phpuaca#29]
5+ reports
<< It's prohibited to access index during event dispatching

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:38)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:674)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:654)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:344)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:624)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:604)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:634)
	at com.jetbrains.php.PhpClassHierarchyUtils.getObject(PhpClassHierarchyUtils.java:392)
	at com.jetbrains.php.PhpClassHierarchyUtils$2.appendNextElements(PhpClassHierarchyUtils.java:54)
	at com.jetbrains.php.PhpClassHierarchyUtils$2.appendNextElements(PhpClassHierarchyUtils.java:44)
	at com.jetbrains.php.PhpClassHierarchyUtils.process(PhpClassHierarchyUtils.java:154)
	at com.jetbrains.php.PhpClassHierarchyUtils.processSuperClasses(PhpClassHierarchyUtils.java:168)
	at com.jetbrains.php.phpunit.PhpUnitUtil.isTestClass(PhpUnitUtil.java:116)
	at com.jetbrains.php.phpunit.PhpUnitUtil.isTestClass(PhpUnitUtil.java:102)
	at com.jetbrains.php.phpunit.PhpUnitUtil.lambda$static$0(PhpUnitUtil.java:49)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findClasses(PhpPsiUtil.java:522)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findClass(PhpPsiUtil.java:511)
	at com.jetbrains.php.phpunit.PhpUnitUtil.findTestClass(PhpUnitUtil.java:216)
	at com.jetbrains.php.phpunit.PhpUnitUtil.isPhpUnitTestFile(PhpUnitUtil.java:230)
	at com.phpuaca.helper.AvailabilityHelper.checkFile(AvailabilityHelper.java:17)
	at com.phpuaca.reference.StringReferenceProvider.getReferencesByElement(StringReferenceProvider.java:16)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:59)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:293)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.getOriginalInternal(PhpClassAliasImpl.kt:61)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.access$getOriginalInternal(PhpClassAliasImpl.kt:33)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl$original$1.compute(PhpClassAliasImpl.kt:45)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl$original$1.compute(PhpClassAliasImpl.kt:33)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.getOriginal(PhpClassAliasImpl.kt:43)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.isAnonymous(PhpClassAliasImpl.kt:144)
	at com.jetbrains.php.lang.psi.PhpBreadcrumbsInfoProvider.getElementInfo(PhpBreadcrumbsInfoProvider.java:42)
	at com.intellij.xml.breadcrumbs.PsiCrumb.<init>(PsiCrumb.java:30)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.getLineElements(BreadcrumbsXmlWrapper.java:314)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.getPresentableLineElements(BreadcrumbsXmlWrapper.java:279)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.updateCrumbs(BreadcrumbsXmlWrapper.java:401)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.updateCrumbs(BreadcrumbsXmlWrapper.java:223)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.access$000(BreadcrumbsXmlWrapper.java:80)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper$1.fileStatusesChanged(BreadcrumbsXmlWrapper.java:113)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.fileStatusesChanged(FileStatusManagerImpl.java:194)
	at mobi.hsz.idea.gitignore.util.CacheMap.refresh(CacheMap.java:194)
	at mobi.hsz.idea.gitignore.util.CacheMap.cleanup(CacheMap.java:180)
	at mobi.hsz.idea.gitignore.IgnoreManager$1.fileDeleted(IgnoreManager.java:171)
	at sun.reflect.GeneratedMethodAccessor1046.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy23.fileDeleted(Unknown Source)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:85)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:374)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy24.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:774)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvent(PersistentFSImpl.java:674)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.deleteFile(PersistentFSImpl.java:456)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.delete(VirtualFileSystemEntry.java:203)
	at com.intellij.psi.impl.file.PsiFileImplUtil.doDelete(PsiFileImplUtil.java:75)
	at com.intellij.psi.impl.source.PsiFileImpl.delete(PsiFileImpl.java:514)
	at com.intellij.ide.util.DeleteHandler.lambda$null$1(DeleteHandler.java:260)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1031)
	at com.intellij.ide.util.DeleteHandler.lambda$null$2(DeleteHandler.java:258)
	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.disableChecksDuring(NonProjectFileWritingAccessProvider.java:180)
	at com.intellij.ide.util.DeleteHandler.lambda$deletePsiElement$3(DeleteHandler.java:193)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:193)
	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:115)
	at com.intellij.ide.projectView.impl.ProjectViewImpl$MyDeletePSIElementProvider.deleteElement(ProjectViewImpl.java:969)
	at com.intellij.ide.actions.DeleteAction.actionPerformed(DeleteAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:623)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:622)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:621)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jdreesen** [comment]
I recommend you to switch to [Daniel Espendiller's fork of this plugin](https://github.com/Haehnchen/idea-php-phpunit-plugin) because it seems that this one is dead.
